from datetime import date, timedelta

DEFAULT_STOCK_TICKERS = "AAPL, MSFT, GOOGL, AMZN, META"
DEFAULT_FACTOR_TICKERS = "SPY, QQQ, IWM, XLF, XLE"
DEFAULT_LOOKBACK_YEARS = 3
DEFAULT_START_DATE = date.today() - timedelta(days=365 * DEFAULT_LOOKBACK_YEARS)
DEFAULT_END_DATE = date.today()
ROLLING_WINDOW_OPTIONS = [30, 60, 90, 120, 252]
DEFAULT_ROLLING_WINDOW = 60
RETURN_METHODS = ["log", "simple"]
DEFAULT_RETURN_METHOD = "log"
CACHE_TTL_SECONDS = 3600

# Hedge optimizer
STRATEGY_OPTIONS = [
    "Minimum Variance",
    "Beta-Neutral",
    "Tail Risk (CVaR)",
    "Risk Parity",
]
DEFAULT_STRATEGY = "Minimum Variance"
DEFAULT_NOTIONAL = 1_000_000.0
DEFAULT_WEIGHT_BOUNDS = (-1.0, 0.0)  # short-only hedging
DEFAULT_CVAR_CONFIDENCE = 0.95
DEFAULT_MIN_HEDGE_NAMES = 3
ANNUALIZATION_FACTOR = 252

# Backtest
DEFAULT_ROLLING_VOL_WINDOW = 60
DEFAULT_RISK_FREE_RATE = 0.05

# Monte Carlo simulation
MC_DEFAULT_HORIZON = 60
MC_HORIZON_OPTIONS = [30, 60, 90, 120, 252]
MC_DEFAULT_NUM_SIMS = 5000
MC_NUM_SIMS_OPTIONS = [1000, 5000, 10000]
MC_PERCENTILE_BANDS = [5, 25, 50, 75, 95]
MC_SPAGHETTI_PATHS = 50
MC_LOSS_THRESHOLDS = [0.05, 0.10]
MC_DEFAULT_SEED = 42
